### ISSUE TITLE
Are these fonts copyrighted?

### ISSUE THREAD

**Issue by RenegadeScooter** [ianhan/BitmapFonts#4]
I'm getting into indie game development, and I was wondering if anyone has the rights to these fonts. Would I need to contact anyone if I used the fonts for a game? If so, who do I contact?

**Comment by hogsy** [comment]
> Are these fonts copyrighted?

Yes. Personally I wouldn't use anything from the main directory under this repo.

The "font-pack" however has a license.

https://github.com/ianhan/BitmapFonts/blob/main/font-pack/license.txt
